#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use App\Console\FakeUsersGenerator;
use App\Console\FakeProductGenerator;

require __DIR__. '/vendor/autoload.php';


$app = new Application("Stubs generator");

$app->addCommands([new FakeUsersGenerator, new FakeProductGenerator]);

$app->run();